#!/usr/bin/env php
<?php

require_once __DIR__.'/../vendor/autoload.php';

use Knp\Bundle\MarkdownBundle\Parser\MarkdownParser;

$app = new Silex\Application();

$app['markdown.parser'] = new MarkdownParser();

//Include the namespaces of the components we plan to use
use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;

//Instantiate our Console application
$console = new Application('Fotelis', '1.0');

//Register a command to run from the command line
//Our command will be started with "./console.php sync"
$console->register( 'gen:mdhtml' )
    ->setDefinition(array(
        new InputArgument('file', InputArgument::REQUIRED, 'Input md file path'),
    ))
    ->setDescription('Generate html from markdown file')
    ->setHelp('Usage: <info>./console gen:mdhtml <INPUT_MD_FILE></info>')
    ->setCode(function(InputInterface $input, OutputInterface $output) use ($app) {
        echo $app['markdown.parser']->transformMarkdown(file_get_contents($input->getArgument('file')));
    });

$console->run();